---
# This role installs and sets up keepalived

- name: Install keepalived (Debian)
  apt: name=keepalived state=latest
  tags: keepalived
  notify: restart keepalived

- name: Send configuration files to keepalived
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service: name=keepalived state=running
  tags: keepalived
