---
- name: 1. install Apache
  apt: name=apache2 state=latest

- name: Install PHP5 modules
  apt: name={{ item }} state=latest
       update_cache=yes
  with_items:
   - php5
   - php5-common
   - php5-cgi
   - php5-cli
   - php5-mysql
   - php5-snmp
   - php5-ffmpeg
   - php5-gd
   - php5-geoip
   - php5-imagick
   - php5-json 

- name: 3. start Apache
  service: name=apache2 state=running enabled=yes
