---
# This role installs HAProxy and configures it.

- name: main | uninstall apache packages
  apt: >
    pkg={{ item }} 
    state=absent
    purge=yes
    force=yes
  with_items:
    - apache2*

- apt_repository: repo='deb http://cdn.debian.net/debian wheezy-backports main' state=present

- name: Download and install haproxy and socat
  apt: name={{ item }} state=present
  with_items:
  - haproxy

#- debug: var=hostvars

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy
